secrets:
  bot_config:
    file: ./secrets/bot_config.json

services:
  bot:
    container_name: bot
    build:
      context: bot
      dockerfile: bot.Dockerfile
    restart: always
    secrets:
      - bot_config

  agent:
    container_name: agent
    build:
      context: agent
      dockerfile: agent.Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
