[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.13",
    "langchain-google-genai>=2.1.5",
    "langchain-tavily>=0.2.4",
    "langchain[google-genai]>=0.3.26",
    "langgraph>=0.4.8",
    "langgraph-checkpoint-sqlite>=2.0.10",
    "langsmith>=0.4.1",
    "websockets>=15.0.1",
]
